name: Release Latest Build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*.yml'
      - 'server/target/*.exe'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: List files to be released
      id: list_files
      run: |
        echo "EXE files:"
        ls -la server/target/*.exe || true

    - name: Find latest MSI and EXE
      id: find_latest
      run: |
        # Find latest EXE (sorted by version)
        LATEST_EXE=$(ls -1 server/target/*.exe | sort -V | tail -n1)
        
        echo "Selected EXE: $LATEST_EXE"
        echo "LATEST_EXE=$LATEST_EXE" >> $GITHUB_ENV

    - name: Generate tag name
      id: generate_tag
      run: |
        TAG_NAME="Release-$(date +'%Y%m%d-%H%M%S')"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: "${{ env.TAG_NAME }}"
        body: |
          Automated release containing latest EXE files.
        files: |
          ${{ env.LATEST_EXE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
